const ShipWeaponList = [{name: "Assault laser cannon",cost: 4150,damage: "2d6 energy",category: "Primary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 15"},{ name: "overheat 2"}],smallerShip: true},
{name: "Blaster cannon",cost: 4000,damage: "1d8 energy",category: "Primary",properties: [{ name: "Power (range 600/2400)"},{ name: "hidden"},{ name: "overheat 18"},{ name: "rapid 9"}],smallerShip: true},
{name: "Burst laser cannon",cost: 4500,damage: "2d4 energy",category: "Primary",properties: [{ name: "Power (range 200/800)"},{ name: "auto"},{ name: "burst 1"},{ name: "overheat 2"},{ name: "saturate"}],smallerShip: true},
{name: "Double laser cannon",cost: 4500,damage: "2d4 energy",category: "Primary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 8"}],smallerShip: true},
{name: "Heavy blaster cannon",cost: 4150,damage: "1d8 energy",category: "Primary",properties: [{ name: "Power (range 600/2400)"},{ name: "heavy"},{ name: "overheat 12"}],smallerShip: true},
{name: "Heavy ion cannon",cost: 4150,damage: "1d10 ion",category: "Primary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 17"},{ name: "heavy"},{ name: "ionizing"},{ name: "overheat 4"}],smallerShip: true},
{name: "Heavy laser cannon",cost: 4150,damage: "1d12 energy",category: "Primary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 15"},{ name: "heavy"},{ name: "overheat 2"}],smallerShip: true},
{name: "Ion cannon",cost: 6100,damage: "2d4 ion",category: "Primary",properties: [{ name: "Power (range 800/3200)"},{ name: "constitution 13"},{ name: "ionizing"},{ name: "overheat 8"}],smallerShip: true},
{name: "Laser cannon",cost: 4000,damage: "1d10 energy",category: "Primary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 11"},{ name: "overheat 4"}],smallerShip: true},
{name: "Light ion cannon",cost: 6100,damage: "1d8 ion",category: "Primary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 16"}],smallerShip: true},
{name: "Light laser cannon",cost: 4100,damage: "1d8 energy",category: "Primary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 16"}],smallerShip: true},
{name: "Quad laser cannon",cost: 4400,damage: "2d4 energy",category: "Primary",properties: [{ name: "Power (range 800/3200)"},{ name: "constitution 13"},{ name: "overheat 8"},{ name: "rapid 2"}],smallerShip: true},
{name: "Quad pulse laser",cost: 4400,damage: "1d6 energy",category: "Primary",properties: [{ name: "Power (range 400/1600)"},{ name: "overheat 16"},{ name: "rapid 4"}],smallerShip: true},
{name: "Plasburst laser cannon",cost: 4000,damage: "1d8 energy",category: "Primary",properties: [{ name: "Power (range 600/2400)"},{ name: "burst 12"},{ name: "overheat 12"}],smallerShip: true},
{name: "Pulse laser cannon",cost: 2500,damage: "1d4 energy",category: "Primary",properties: [{ name: "Power (range 500/2000)"},{ name: "keen 1"},{ name: "piercing 1"},{ name: "overheat 20"}],smallerShip: true},
{name: "Rapid-fire laser cannon",cost: 4600,damage: "1d6 energy",category: "Primary",properties: [{ name: "Power (range 400/1600)"},{ name: "auto"},{ name: "burst 16"},{ name: "overheat 16"},{ name: "rapid 4"}],smallerShip: true},
{name: "Slug cannon",cost: 4000,damage: "1d8 kinetic",category: "Primary",properties: [{ name: "Power (range 600/2400)"},{ name: "constitution 11"},{ name: "dire 1"},{ name: "overheat 4"}],smallerShip: true},
{name: "Sparkler ion cannon",cost: 6100,damage: "1d4 ion",category: "Primary",properties: [{ name: "Power (range 200/800)"},{ name: "auto"},{ name: "burst 1"},{ name: "ionizing"},{ name: "overheat 1"},{ name: "saturate"}],smallerShip: true},
{name: "Thermite cannon",cost: 6300,damage: "1d12 fire",category: "Primary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 17"},{ name: "melt"},{ name: "overheat 2"}],smallerShip: true},
{name: "Twin auto-blaster",cost: 4400,damage: "1d4 energy",category: "Primary",properties: [{ name: "Power (range 250/1000)"},{ name: "auto"},{ name: "burst 10"},{ name: "hidden"},{ name: "overheat 20"},{ name: "rapid 5"}],smallerShip: true},
{name: "Twin laser cannon",cost: 4400,damage: "1d8 energy",category: "Primary",properties: [{ name: "Power (range 600/2400)"},{ name: "constitution 11"},{ name: "rapid 3"},{ name: "overheat 12"}],smallerShip: true},
{name: "Ion railgun",cost: 5700,damage: "1d10 ion",category: "Secondary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 17"},{ name: "ionizing"},{ name: "overheat 4"}],smallerShip: true},
{name: "Particle beam",cost: 5750,damage: "2d4 energy",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "constitution 11"},{ name: "overheat 4"}],smallerShip: true},
{name: "Slug railgun",cost: 5150,damage: "1d12 kinetic",category: "Secondary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 15"},{ name: "overheat 2"}],smallerShip: true},
{name: "Thermite railgun",cost: 5400,damage: "1d10 fire",category: "Secondary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 17"},{ name: "melt"},{ name: "overheat 2"}],smallerShip: true},
{name: "Turbolaser",cost: 5000,damage: "1d10 energy",category: "Secondary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 13"},{ name: "overheat 4"}],smallerShip: true},
{name: "Cluster pod launcher",cost: 6000,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"},{ name: "reload 12"}],smallerShip: true},
{name: "Missile launcher",cost: 6250,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"},{ name: "reload 4"}],smallerShip: true},
{name: "Torpedo launcher",cost: 6900,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"}],smallerShip: true},
{name: "Bomb deployer",cost: 8000,damage: "-",category: "Quaternary",properties: [{ name: "Ammunition"},{ name: "reload 4"}],smallerShip: true},
{name: "Blaster point-defense",cost: 4000,damage: "3d4 energy",category: "Primary",properties: [{ name: "Power (range 200/800)"},{ name: "saturate"},{ name: "zone"}],smallerShip: false},
{name: "Ion cannon point-defense",cost: 5500,damage: "2d6 ion",category: "Primary",properties: [{ name: "Power (range 300/1200)"},{ name: "ionizing"},{ name: "saturate"},{ name: "zone"}],smallerShip: false},
{name: "Laser cannon point-defense",cost: 6000,damage: "3d6 energy",category: "Primary",properties: [{ name: "Power (range 300/1200)"},{ name: "saturate"},{ name: "zone"}],smallerShip: false},
{name: "Ordnance point-defense",cost: 6000,damage: "2d6 kinetic",category: "Primary",properties: [{ name: "Power (range 300/1200)"},{ name: "explosive"},{ name: "saturate"},{ name: "zone"}],smallerShip: false},
{name: "Assault turbolaser battery",cost: 4150,damage: "6d6 energy",category: "Secondary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 15"},{ name: "overheat 2"}],smallerShip: false},
{name: "Burst turbolaser battery",cost: 4500,damage: "6d4 energy",category: "Secondary",properties: [{ name: "Power (range 200/800)"},{ name: "auto"},{ name: "burst 1"},{ name: "overheat 2"},{ name: "saturate"}],smallerShip: false},
{name: "Double turbolaser battery",cost: 4500,damage: "6d4 energy",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 8"}],smallerShip: false},
{name: "Heavy ion battery",cost: 4150,damage: "3d10 ion",category: "Secondary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 17"},{ name: "heavy"},{ name: "ionizing"},{ name: "overheat 4"}],smallerShip: false},
{name: "Heavy ion railgun",cost: 5700,damage: "3d10 ion",category: "Secondary",properties: [{ name: "Power (range 2000/8000)"},{ name: "constitution 19"},{ name: "ionizing"},{ name: "overheat 4"}],smallerShip: false},
{name: "Heavy gun battery",cost: 4000,damage: "4d10 kinetic",category: "Secondary",properties: [{ name: "Power (range 400/1600)"},{ name: "constitution 17"},{ name: "overheat 1"},{ name: "vicious 1"}],smallerShip: false},
{name: "Heavy slug railgun",cost: 5150,damage: "3d12 kinetic",category: "Secondary",properties: [{ name: "Power (range 2400/9600)"},{ name: "constitution 17"},{ name: "overheat 2"}],smallerShip: false},
{name: "Heavy thermite railgun",cost: 5400,damage: "3d10 fire",category: "Secondary",properties: [{ name: "Power (range 2400/9600)"},{ name: "constitution 19"},{ name: "melt"},{ name: "overheat 2"}],smallerShip: false},
{name: "Heavy turbolaser battery",cost: 4150,damage: "3d12 energy",category: "Secondary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 15"},{ name: "heavy"},{ name: "overheat 2"}],smallerShip: false},
{name: "Ion battery",cost: 6100,damage: "6d4 ion",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "constitution 13"},{ name: "ionizing"},{ name: "overheat 8"}],smallerShip: false},
{name: "Light ion battery",cost: 6100,damage: "3d8 ion",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 16"}],smallerShip: false},
{name: "Light turbolaser battery",cost: 4100,damage: "3d8 energy",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "overheat 16"}],smallerShip: false},
{name: "Long-range turbolaser battery",cost: 4000,damage: "3d10 energy",category: "Secondary",properties: [{ name: "Power (range 2400/9600)"},{ name: "constitution 15"},{ name: "overheat 2"}],smallerShip: false},
{name: "Quad turbolaser battery",cost: 4400,damage: "6d4 energy",category: "Secondary",properties: [{ name: "Power (range 800/3200)"},{ name: "constitution 13"},{ name: "overheat 8"},{ name: "rapid 2"}],smallerShip: false},
{name: "Quad pulse turbolaser battery",cost: 4400,damage: "2d6 energy",category: "Secondary",properties: [{ name: "Power (range 400/1600)"},{ name: "overheat 16"},{ name: "rapid 4"}],smallerShip: false},
{name: "Particle Cannon",cost: 5750,damage: "6d4 energy",category: "Secondary",properties: [{ name: "Power (range 1600/6400)"},{ name: "constitution 13"},{ name: "overheat 4"}],smallerShip: false},
{name: "Plasburst turbolaser battery",cost: 4000,damage: "3d8 energy",category: "Secondary",properties: [{ name: "Power (range 600/2400)"},{ name: "burst 12"},{ name: "overheat 12"}],smallerShip: false},
{name: "Pulse turbolaser battery",cost: 2500,damage: "3d4 energy",category: "Secondary",properties: [{ name: "Power (range 500/2000)"},{ name: "keen 1"},{ name: "piercing 1"},{ name: "overheat 20"}],smallerShip: false},
{name: "Rapid-fire turbolaser battery",cost: 4600,damage: "3d6 energy",category: "Secondary",properties: [{ name: "Power (range 400/1600)"},{ name: "auto"},{ name: "burst 16"},{ name: "overheat 16"},{ name: "rapid 4"}],smallerShip: false},
{name: "Thermite battery",cost: 6300,damage: "3d12 fire",category: "Secondary",properties: [{ name: "Power (range 1200/4800)"},{ name: "constitution 17"},{ name: "melt"},{ name: "overheat 2"}],smallerShip: false},
{name: "Turbolaser battery",cost: 4000,damage: "3d10 energy",category: "Secondary",properties: [{ name: "Power (range 1000/4000)"},{ name: "constitution 11"},{ name: "overheat 4"}],smallerShip: false},
{name: "Twin turbolaser battery",cost: 4400,damage: "2d8 energy",category: "Secondary",properties: [{ name: "Power (range 600/2400)"},{ name: "constitution 11"},{ name: "rapid 3"},{ name: "overheat 12"}],smallerShip: false},
{name: "Assault cluster pod launcher",cost: 6000,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"},{ name: "reload 24"}],smallerShip: false},
{name: "Assault missile launcher",cost: 6250,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"},{ name: "reload 8"}],smallerShip: false},
{name: "Assault torpedo launcher",cost: 6900,damage: "-",category: "Tertiary",properties: [{ name: "Ammunition"}],smallerShip: false},
{name: "Bomb layer",cost: 8000,damage: "-",category: "Quaternary",properties: [{ name: "Ammunition"},{ name: "reload 8"}],smallerShip: false},
]

export default ShipWeaponList;